travis:
  secure:
    BINSTAR_TOKEN: foPzB86r4WNKdWwhCxH9qS4lLs0MSCF8eI8RqtbrU0b/S0EhT0l4Z2Rls4LBUykAyJfxfQTrG/y7mMAFjdUhEELfL1ufSg8rJHRirPaFTzd0Qgy6T/5m9P4mdU4W8NxptNTWFj66/0FNCQYn4twD7suFWcnLkpymmpipB4H0qPz4ebhXchZRv5Yk/BZXzaSZSrM7VHJUTgaSoiSkNuZM8sgv0/NDXgtHayd0cXkV67HDqrhJ70HlLOFuThTZwfQdOv57awmB6TZB17FhFxcDJlNfu1BjPO7CgHfK4SRquQYDFTGFsuxumqz6jnn0YdEgyI61iLrwyBL6SrvFQTiJChlQWKmLA01D/5yNM4nK33/WT3h4UKOHu6gELeSLkEnVap8B6JnIwV928LxS5z+cn1DG/C+qASVXkUh9/26qMbBsdj1zcFVEKOrT5UPJNfoY94S0DAsI4PJVP0MVH0uAht5AsuiYKe0pPtJX6NXWeaMdZq9wvmmMn+38BkNGXmds5Ye3np+AefrtwEnZBY/foB4idSh/wp+f2nJIqxcKDD37DrBDhUjEjE4NvIVejVVmX08fy6mtWYBcjpRR8Cc2H7jztxxddDXGpR3ab+PbbYZLEVyDwmEowHSC86UI3mbFV7sL4ScODLgOMZHH8gp9fNZRfmrfZVi58ka2JurFyKY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
